# Generated by Django 4.1.1 on 2022-10-28 12:39

import apps.admin_suppliers_and_others.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Company Name')),
                ('fullname', models.CharField(max_length=30, verbose_name='Person In Charge')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('office', models.CharField(blank=True, max_length=15, null=True, verbose_name='Office Phone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('email2', models.EmailField(max_length=100, verbose_name='Second Email')),
                ('no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plate Number')),
                ('level', models.CharField(blank=True, max_length=10, null=True, verbose_name='Floor Number')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('Country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('field', models.CharField(choices=[('Poultry', 'Poultry'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Greens', 'Greens'), ('Others', 'Others')], max_length=20)),
                ('others', models.CharField(blank=True, max_length=20, null=True, verbose_name='Other Fields')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('active', models.BooleanField(default=False, verbose_name='Is Supplier Active?')),
                ('register', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
                ('info_update', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('file_upload', models.FileField(default='no file available', upload_to=apps.admin_suppliers_and_others.models.upload_file, verbose_name='Product pdf')),
                ('comment', models.TextField(verbose_name='Admin Comments')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Registered Supplier')),
            ],
        ),
    ]
