# Generated by Django 4.1.1 on 2022-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_model',
            name='email2',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Second Email'),
        ),
    ]
