# Generated by Django 4.1.1 on 2022-10-28 13:32

import apps.admin_suppliers_and_others.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_suppliers_and_others', '0002_alter_supplier_model_email2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='2nd Phone')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('employment_period', models.DateField()),
                ('reference_info', models.CharField(max_length=200, null=True)),
                ('level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Supervisor', 'Supervisor'), ('Assistant Manager', 'Assistant Manager'), ('Manager', 'Manager'), ('Director', 'Director')], max_length=20)),
                ('employed', models.BooleanField(default=False)),
                ('register', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
                ('info_update', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('file_upload', models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee documents')),
                ('comment', models.TextField(verbose_name='Admin Comments')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Registered Supplier')),
            ],
        ),
    ]
