# Generated by Django 4.1.1 on 2022-10-28 13:39

import apps.admin_suppliers_and_others.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0004_employee_model_phone2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_model',
            old_name='file_upload',
            new_name='file_upload5',
        ),
        migrations.AddField(
            model_name='employee_model',
            name='file_upload1',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee Passport'),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='file_upload2',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee cv'),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='file_upload3',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee Image'),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='file_upload4',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee Contract'),
        ),
    ]
