# Generated by Django 4.1.1 on 2022-10-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0005_rename_file_upload_employee_model_file_upload5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='file_upload2',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='file_upload3',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='file_upload4',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='file_upload5',
        ),
    ]
