# Generated by Django 4.1.1 on 2022-10-29 03:22

import apps.admin_suppliers_and_others.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0006_remove_employee_model_file_upload2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='file_upload2',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee cv'),
        ),
    ]
