# Generated by Django 4.1.1 on 2022-10-29 03:27

import apps.admin_suppliers_and_others.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0007_employee_model_file_upload2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='file_upload3',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee Image'),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='file_upload4',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='Employee Contract'),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='file_upload5',
            field=models.FileField(default='no documents available', upload_to=apps.admin_suppliers_and_others.models.emp_upload_file, verbose_name='other documents'),
        ),
    ]
