# Generated by Django 4.1.1 on 2022-10-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0009_alter_employee_model_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier_model',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelTable(
            name='employee_model',
            table='Employee Profile',
        ),
        migrations.AlterModelTable(
            name='supplier_model',
            table='Supplier Profile',
        ),
    ]
