# Generated by Django 4.1.1 on 2022-10-29 04:07

import apps.admin_suppliers_and_others.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_suppliers_and_others', '0010_alter_supplier_model_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Profile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Company Name')),
                ('fullname', models.CharField(max_length=30, verbose_name='Person In Charge')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('office', models.CharField(blank=True, max_length=15, null=True, verbose_name='Office Phone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('active', models.BooleanField(default=False, verbose_name='Is Supplier Active?')),
                ('register', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
                ('info_update', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('file_upload', models.FileField(default='no file available', upload_to=apps.admin_suppliers_and_others.models.upload_file, verbose_name='Client documetn')),
                ('comment', models.TextField(verbose_name='Admin Comments')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Registered Supplier')),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Clients Profile',
                'db_table': 'Client_Profile',
            },
        ),
    ]
