# Generated by Django 4.1.1 on 2022-10-29 07:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_suppliers_and_others', '0011_client_profile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Comments'),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='2nd Phone'),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='reference_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Employee_payroll_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30, verbose_name='Employee Position')),
                ('basic', models.IntegerField(verbose_name='Basic Salary')),
                ('up_sell', models.IntegerField(default=0, verbose_name='Product Up Sell')),
                ('allowance', models.IntegerField(default=0, verbose_name='Allowance')),
                ('child_no', models.IntegerField(default=0, verbose_name='No Of Child')),
                ('child_allowance', models.IntegerField(default=0, verbose_name='Child Allowance')),
                ('insurance_carried_company', models.IntegerField(verbose_name=' Insurance Carried Company')),
                ('insurance_carried_employee', models.IntegerField(verbose_name=' Insurance Carried Employee')),
                ('retirement', models.IntegerField(verbose_name='Retirement')),
                ('unclaimed_vacation_days', models.IntegerField(default=0, verbose_name='Unclaimed Vacation Days')),
                ('unclaimed_vacation', models.IntegerField(default=0, verbose_name='Unclaimed Vacation')),
                ('deduction_tax', models.IntegerField(verbose_name='Deduction Tax')),
                ('absense_days', models.IntegerField(default=0, verbose_name='Absense Days')),
                ('deduction_absense', models.IntegerField(default=0, verbose_name='Deduction Absense')),
                ('cash_in_hand', models.IntegerField(default=0, verbose_name='Cash In Hand')),
                ('month_end', models.DateField(default=datetime.datetime(2022, 10, 29, 15, 36, 5, 436723), verbose_name='Choose Month End')),
                ('register', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
                ('info_update', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_suppliers_and_others.employee_model')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Registered Supplier')),
            ],
            options={
                'verbose_name': 'Employee Payroll',
                'verbose_name_plural': 'Employees payroll',
                'db_table': 'Employee Payroll',
            },
        ),
    ]
