# Generated by Django 4.1.1 on 2022-10-29 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0012_alter_employee_model_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='deduction_tax',
            field=models.IntegerField(default=0, verbose_name='Deduction Tax'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='month_end',
            field=models.DateField(default=datetime.datetime(2022, 10, 29, 20, 7, 37, 545277), verbose_name='Choose Month End'),
        ),
    ]
