# Generated by Django 4.1.1 on 2022-10-29 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0013_alter_employee_payroll_model_deduction_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='absense_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Absense Days'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='allowance',
            field=models.PositiveIntegerField(default=0, verbose_name='Allowance'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='basic',
            field=models.PositiveIntegerField(verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='cash_in_hand',
            field=models.PositiveIntegerField(default=0, verbose_name='Cash In Hand'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='child_allowance',
            field=models.PositiveIntegerField(default=0, verbose_name='Child Allowance'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='child_no',
            field=models.PositiveIntegerField(default=0, verbose_name='No Of Child'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='deduction_absense',
            field=models.PositiveIntegerField(default=0, verbose_name='Deduction Absense'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='deduction_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Deduction Tax'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='insurance_carried_company',
            field=models.PositiveIntegerField(verbose_name=' Insurance Carried Company'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='insurance_carried_employee',
            field=models.PositiveIntegerField(verbose_name=' Insurance Carried Employee'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='month_end',
            field=models.DateField(default=datetime.datetime(2022, 10, 29, 20, 11, 14, 749457), verbose_name='Choose Month End'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='retirement',
            field=models.PositiveIntegerField(verbose_name='Retirement'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='unclaimed_vacation',
            field=models.PositiveIntegerField(default=0, verbose_name='Unclaimed Vacation'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='unclaimed_vacation_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Unclaimed Vacation Days'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='up_sell',
            field=models.PositiveIntegerField(default=0, verbose_name='Product Up Sell'),
        ),
    ]
