# Generated by Django 4.1.1 on 2022-10-29 13:18

import apps.admin_suppliers_and_others.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0015_employee_model_emp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='emp_code',
            field=models.CharField(default=apps.admin_suppliers_and_others.models.emp_code, max_length=30, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='month_end',
            field=models.DateField(default=datetime.datetime(2022, 10, 29, 21, 18, 0, 343015), verbose_name='Choose Month End'),
        ),
    ]
