# Generated by Django 4.1.1 on 2022-10-31 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_suppliers_and_others', '0016_alter_employee_model_emp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_payroll_model',
            name='net_salary',
            field=models.PositiveIntegerField(default=0, verbose_name='Net Salary'),
        ),
        migrations.AlterField(
            model_name='employee_payroll_model',
            name='month_end',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 16, 54, 39, 500918), verbose_name='Choose Month End'),
        ),
    ]
