# Generated by Django 4.1.1 on 2022-10-26 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('short_des', models.TextField()),
                ('description', models.TextField()),
                ('image', models.CharField(default='images/product/', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('view_number', models.IntegerField()),
                ('published', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=10)),
                ('order_quantity', models.PositiveIntegerField()),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
