# Generated by Django 4.1.1 on 2022-11-03 10:36

import apps.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('short_des', models.TextField(verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to=apps.blog.models.image_path, verbose_name='Image')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Registered')),
                ('uppdated', models.DateTimeField(auto_now=True, verbose_name='Uppdated')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('view_counter', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('like_counter', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('user_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Registered')),
            ],
        ),
    ]
