# Generated by Django 4.1.1 on 2022-10-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us_model',
            name='user_register',
        ),
    ]
